client_config_backend: file
client_config:
    client_id: 322908322161-a1rglrqb8j71eprpbhtjok99g902gr78.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive